<?php

return [
    'SOLIDINVOICE_APPLICATION_URL' => null,
    'SOLIDINVOICE_APP_SECRET' => null,
    'SOLIDINVOICE_BUILD_ID' => null,
    'SOLIDINVOICE_DATABASE_DRIVER' => null,
    'SOLIDINVOICE_DATABASE_HOST' => null,
    'SOLIDINVOICE_DATABASE_NAME' => null,
    'SOLIDINVOICE_DATABASE_PASSWORD' => null,
    'SOLIDINVOICE_DATABASE_PORT' => null,
    'SOLIDINVOICE_DATABASE_USER' => null,
    'SOLIDINVOICE_DATABASE_VERSION' => null,
    'SOLIDINVOICE_ENABLE_TELEMETRY' => null,
    'SOLIDINVOICE_LOCALE' => null,
];
